hydroframe/hf_hydrodata

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
if the option "mask":"true" is specified to the function get_gridded_data() then mask the result by the HUC specified by the "huc_id" option. If grid_bounds or lat long_bounds is specified then mask the result by the conus borders contained in the bounds.
Also, when a TIFF file is generated by get_gridded_files() write the file using the origin at top left as is typical for tiff files. This is the implementation for issue-142.
Verify with new unit tests. Also verify on Verde with hydrodata using get_gridded_files() to generate and display tiff files with mask:true to verify that the image is masked by the call to get_gridded_data from get_gridded_files().
> Issue 142 - support masking results from get_gridded_data().

- pyproject.toml
- src/hf_hydrodata/gridded.py
Fix some issues with get_gridded_files reading 2D tiff files.
Add thread lock protection around calls to xarray open_dataset. The open_dataset call in xarray is not thread safe even though using the dataset returned by open_dataset is thread safe.
> Fix issues with get_gridded_files reading 2D tiff files and some thread safety issues

- pyproject.toml
- src/hf_hydrodata/data_catalog.py
- src/hf_hydrodata/gridded.py
- src/hf_hydrodata/model/data_catalog_entry.csv
- tests/hf_hydrodata/test_gridded.py
Added an entry to the data catalog for a file used by hydrogen emulator static parameters.
* Added the PFB entry for topographic_index variable for conus1.
* Fixed the code that picks preferred entries when there are multiple file_types for a filter. The old code didn't work with two many options that was triggered by adding this new entry
* Fixed some code when reading 2D static files triggered by reading this new static PFB file. 
* Removed entry 89 from data catalog that was a duplicate entry for topographic_index variable for pfmetadata files.
> Add PFB topographic_index entry

- docs/source/available_metadata.rst
- docs/source/point_data/point_methods.rst
- pyproject.toml
- src/hf_hydrodata/point.py
Renames conus x/y variables to conus i/j to reflect that they represent the integer number of grid cells away from the named conus grid origin. This PR also includes a small number of documentation edits.
> Rename conus mapping variables

- pyproject.toml
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_point.py
This Pull Request adds additional functionality for the hf_hydrodata.point module. Users can now use the parameter "grid" to specify a grid of either "conus1" or "conus2" and the parameter "grid_bounds" to filter observations that fall within a provided i/j bounding box for that grid. The naming conventions and input structure match comparable parameters used in the gridded module.
> Add feature to filter point observations on grid bounds

- pyproject.toml
- src/hf_hydrodata/gridded.py
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_gridded.py
Fix a bug that occurs if you omit temporal_resolution from a call to get_gridded_files(), but when the temporal_resolution is not ambiguous and is unnecessary to pass to the function.
Also removed some print() statements left in from some previous commits.
> fix bug when omitting temporal_resolution

- pyproject.toml
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_point.py
This Pull Request adds some additional variables to the DataFrame returned from the `point.get_site_variables()` function. The additional variables include the dataset name, temporal resolution, aggregation, and variable name as they would be input as parameters into the `get_point_data()` or `get_point_metadata()` functions. The conus1 and conus2 grid mappings are also merged on. 
These updates are being made to support the "get observations" step in the HydroGEN project model evaluation framework development.
> Add variables to point.get_site_variables() output

- pyproject.toml
- src/hf_hydrodata/grid.py
Change to_ij() method to truncate instead of round.
Add an epsilon to the floating point number before truncating, this allows converting from int to float and back to in to get the same value again, but still the truncate instead of round is more correct.
> truncate instead of round in to_ij

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
Fix a problem in get_gridded_data that uses parflow read_pfb_sequence() to read pfb files.
It turns out that this does not work if the number of files passed in the sequence it too large (> 100 or so).
It returned, but not always with the correct data so this was messing up line charts in hydrogen point observations.
This is fixed in this PR by reading blocks of files with read_pfb_sequence and appending together the results.
There is a unit test to replicate the old problem that is fixed by this PR.
> fix problem with limit of files passed to read_pfb_sequence

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
Change the way NetCDF files are created by get_gridded_files() to match what Nick expected when using it.
The new strategy populates the variables in the NetCDF file with a single water year of 365/366 day entries for daily files
or 365/366 * 24 hour entries for hourly or 12 month entries for month.
Each time dimension in the NetCDF file would always start at the beginning of the water year and populate with data requested in the query. It also fills in time coordinate times in the NetCDF file, but with this strategy the user would know the time based on the dimension index.
> fix get_gridded_files for .nc files

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
Fix algorithm for get_huc_bbox() to use a simpler algorithm that just gets the min/max indexes.
This replaces the previous algorithm that used numpy diff. The two algorithm produce the same result
for most HUC except for level 2 HUC 15 for which the old algorithm returned the wrong box.
Updated unit tests for get_huc_bbox so the tests pass when run both the the old float32 tiff files and new int tiff files.
This allows the unit tests to pass now before we publish the new int tiff boundary files and also after we publish.
Also, added compression to get_gridded_files() when generating NetCDF files.
> compress .nc file for get_gridded_files

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
Add retry logic if hf_hydrodata when API call to get data returns a 500 error.
This only does one retry in case it is a real error, but it the error was a timeout error because slow GPFS with files not cached the second retry is usually very fast because the files are then cached.
I will add a test case to the gridded_tests/test_gridded.py file in the hydroframe-ml/perfm_testing repo since this scenario cannot be tested as a unit test because it is a performance problem that only happens when running remotely.
> add retry logic in gridded data API call

- pyproject.toml
- src/hf_hydrodata/data_catalog.py
- src/hf_hydrodata/data_model_access.py
- src/hf_hydrodata/gridded.py
Modify so that we can call the data catalog URL without an API pin to get the public version of the data catalog.
This was required so the read-the-docs generate could get the data catalog information for public documentation.
This API pin is now optional for the call to get data catalog information, but still required for calls to get data.
> allow readthedocs build to read data catalog

- pyproject.toml
- src/hf_hydrodata/gridded.py
Update to pass schema to URL when calling get_gridded_data().
Before it passed schema in the API call to get the data catalog, but not for the get_gridded_data() URL.
This is necessary so the unit tests all use the development schema when running tests.
> pass schema when getting gridded_data

- pyproject.toml
- src/hf_hydrodata/data_model_access.py
- tests/hf_hydrodata/test_data_catalog.py
- tests/hf_hydrodata/test_gridded.py
- tests/hf_hydrodata/test_point.py
Fix an issue that hf_hydrodata gives an error about unregistered API if you have a an invalid registered PIN when you run on verde if you have an invalid PIN registered. This scenario is created by subsettools when you run subset tools in verde. Subsettools example automatically register a PIN which is in invalid until you register it. But you do not need the PIN on verde so this is annoying.
This change fixes this issue.
This also includes changes to tests to allow tests to run on verde when the verde user account does not have a registered PIN. Some tests that required a registered PIN were removed and these tests will later be added to a test suite running on a remote server.
There is also a new Jenkins job to test this issue by running hf_hydrodata on verde with and without an invalid …
> fix issue with a invalid registered pin when using verde

- pyproject.toml
- src/hf_hydrodata/data_model_access.py
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
Change _apply_mask function from get_gridded_data() so that it does not mask the value of vegm files.
The vegm file is returned by the variable "clm_run".
This fixes a problem in subset tools that subsets the vegm file and writes it to a file for use by parflow.
Since the file used by parflow is a .dat text file the NaNs created by the mask create an error when trying to save.
> Do not mask vegm with get_gridded_data()

- pyproject.toml
- src/hf_hydrodata/gridded.py
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_point.py
This PR removes hard-coding done in the point module in favor of utilizing `hf.get_catalog_entry` to get information on file paths and internal file variable names. All of our current tests should continue to pass; this is changing how files/data are found in the point module but is not adding or changing any user-facing features.
Some small linting in `gridded.py` got carried over as well.
> Use data catalog in point module

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
Add check if user passes variables as string instead of a list to use the string as a single value of a list.
This also initialized the variable file_name which caused an ugly stack trace in some error scenarios.
> fix error handling of get_gridded_files()

- pyproject.toml
- tests/hf_hydrodata/test_gridded.py
I am adding a new private dataset that includes an additional variable, `parflow_evaptrans` on the CONUS2 grid. This PR updates the test to be more flexible when considering the counts of variables we're expecting to query from the data catalog.
> update variable count test

- pyproject.toml
- src/hf_hydrodata/data_catalog.py
- tests/hf_hydrodata/test_data_catalog.py
Add an API call to the register_api_pin() function in hf_hydrodata to validate that the email/pin is correctly registered and valid.
This prevents users from making the mistake of registering a different email address than they registered with the UI and then getting misleading error messages later when remote calls do not work (this happened to Laura).
> Register api validate pin

- pyproject.toml
- tests/hf_hydrodata/test_gridded.py
- tests/hf_hydrodata/test_point.py
Fix some unit tests that started failing because we released new huc boundary files.
> fix tests because of huc_boundary file changes

- docs/dataset_text.yaml
This PR adds a section to the CW3E dataset documentation regarding the underlying source of CW3E product used (retrospective vs. near real time). Before opening this PR, I confirmed the ReadtheDocs page compiles locally and is formatted correctly.
> update dataset docs

- pyproject.toml
- tests/hf_hydrodata/test_gridded.py
The test `test_gridded:test_ambiguous_filter` is sometimes failing because it is looking for a specific variable suggestion (downward_longwave). Sometimes a set of other (still-appropriate) variables are suggested that does not include downward_longwave, which causes this test to fail.
This PR adds flexibility to this test to check against the full list of appropriate suggestions.
This is an example of the failing test.
> Add flexibility to ambiguous filter test

- .github/workflows/run-unit-tests.yaml
- docs/source/available_metadata.rst
- docs/source/point_data/examples/example_site_networks.ipynb
- pyproject.toml
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_point.py
This PR corresponds to efforts to expand and update the CONUS2 i/j mapping values for stream gages (`conus2_i`, `conus2_j`). For reproducibility purposes, we are preserving the previous i/j values in the new metadata fields `conus2_i_nwm` and `conus2_j_nwm`. This PR adds documentation for those metadata fields and adds them to the set of variables included in stream gage metadata returned to the user. Several test bounds are expanded to account for many more gages having `conus2_i` and `conus2_j` values.
Additionally, this PR adds support for a new network list: `nwm`. This network list corresponds to the subset of stream gages that previously had CONUS2 i/j mappings. The purpose for adding this set of gages as a network list is to help users easily filter on only those gages that …
> update CONUS2 i/j grid values; add nwm site network

- docs/source/available_metadata.rst
- pyproject.toml
- tests/hf_hydrodata/test_point.py
This PR fixes two tests within the point module. These tests now accommodate the changed number of sites within a HUC, following the previous change that increased the number of gages with grid mappings.
Also included is a small docs update, to place the new CONUS2 i/j grid variables within the stream gage attributes section. These variables are only returned for stream gages, not all point site types.
> Fix point tests

- docs/generate_docs.py
- pyproject.toml
Fix the generation of the read-the-docs for docs citations links.
Change the read-the-docs generation so if the data catalog entry already contains https:// then use the entry as the link, otherwise add the https://doi.org prefix to construct a valid citation URL link to the reference.
Previously only paper_dois entry got the https://doi.org prefix, but dataset_dois did not. However, the data catalog had entries with and without in both categories. This change makes the entries in the data catalog more robust.
> fix generation of doi citations

- pyproject.toml
Add a dependency module "typing_extensions" that is now required by the most recent xarray and rioxarray.
The lack of this dependency broke a Jenkins job after installing the most recent hf_hydrodata.
> add typing extensions that is now required by rasterio and xarray

- pyproject.toml
- tests/hf_hydrodata/test_point.py
We released updated `conus2_i` and `conus2_j` metadata values today (for stream gages only) after reviewing existing values against known stream locations.
These mappings impact the number of sites that get filtered via HUCs. HUC filtering uses the `conus2_i` and `conus2_j` grid locations for point filtering. This PR updates the tests of stream gage site counts within a single HUC to account for the different mappings. This change is expected.
> update stream gage count in HUC filter tests

- pyproject.toml
- src/hf_hydrodata/gridded.py
- tests/hf_hydrodata/test_gridded.py
This code fixes a bug encountered when running certain code (test case: `gridded.py/test_gridded_files_crs_subgrid`) from a local user machine (via the API). The options dictionary was being left as a string and this caused later logic to not be implemented as expected.
This resulted in a failing test when running via GitHub Actions. 
This PR also adjusts some of the tests to use `pytest.approx` for comparison purposes.
> fix options dict passed via api

- pyproject.toml
- utils/update_dates_from_hydrodata.py
This PR adds a function that updates the end dates for the CW3E version 1.0 dataset in the data catalog. We now intake and pre-process this dataset weekly. This new function adds logic for determining the appropriate end dates for this CW3E version 1.0 dataset so that `hf_hydrodata` users can access the most recent data available.
> update cw3e end dates in data catalog

- pyproject.toml
- src/hf_hydrodata/gridded.py
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_gridded.py
Support the environment variable HUC_VERSION to cause the get_huc_bbox() function to return the HUC boundaries using the dataset_version specified by the environment variables. The values 2025_06, 2025_01, 2024_11 are supported as well as blank or null to use the latest version of the HUC boundary files. The new dataset_version entries were added to the SQL data catalog to support this.
This should work both locally and remotely since the environment variable is used to add the dataset_version parameters to calls to get_gridded_data() locally which is then passed in the API call.
This PR also fixes an obscure issue in get_gridded_files when requested to create a .nc file that contained multiple aggregation values.  This occurred when the aggregation was not specified in the input filter …
> Huc version

- pyproject.toml
- src/hf_hydrodata/data_catalog.py
- src/hf_hydrodata/gridded.py
- src/hf_hydrodata/point.py
- tests/hf_hydrodata/test_gridded.py
- utils/public_release.ddl
Fix the preferred value logic for dataset_version to select "" or None or 1.0 as preferred values to make the correct default work for the new huc_mapping dataset_versions. This should fix the failing unit test in subset tools that uses this.
Also fix the race condition issue with reading parallel aggregation files in get_gridded_files().
This was fixed by moving the copy_options variable inside the aggregation loop so the different modified values for different aggregations were not overwritten when multiple aggregations were loaded in parallel.
> Default huc version

- pyproject.toml
- src/hf_hydrodata/gridded.py
This PR is to fix an error encountered in our regular test suite. This is related to writing of NetCDF files. It appears that this issue is with using the scipy backend for writing files. This PR specifies the backend explicitly to use `engine="netcdf4"`.
```
def test_multiple_aggregations(tmp_path):
"""Test that we can get_gridded_files with multiple aggregations."""
cd = os.getcwd()
os.chdir(tmp_path)
variables = ["precipitation", "air_temp", "downward_shortwave"]
bounds = [500, 500, 502, 502]
start_time = datetime.datetime(1991, 8, 4)
end_time = start_time + datetime.timedelta(days=2)
options = {
"dataset": "CW3E",
"grid_bounds": bounds,
"temporal_resolution": "daily",
"start_time": start_time,
"end_time": end_time,
}
assert not os.path.exists("foo.nc")
> …
```
> specify backend for writing netcdf
